name: Build

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    env:
      CIBW_SKIP: cp27-win* pp27-win*

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'

      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install git+https://github.com/joerick/cibuildwheel.git@f6eaa9f
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_wheels_python27_windows_64:
    name: Build wheel for python2.7 on windows-latest 64 bit
    runs-on: windows-latest
    env:
      CIBW_BUILD: cp27-win_amd64
      DISTUTILS_USE_SDK: 1
      MSSdk: 1

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'

      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install git+https://github.com/joerick/cibuildwheel.git@f6eaa9f

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build 64-bit wheel
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl


  build_wheels_python27_windows_32:
    name: Build wheel for python2.7 on windows-latest 32 bit
    runs-on: windows-latest
    env:
      CIBW_BUILD: cp27-win32 pp27-win32
      DISTUTILS_USE_SDK: 1
      MSSdk: 1

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'

      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install git+https://github.com/joerick/cibuildwheel.git@f6eaa9f

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Build 64-bit wheel
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

