name: Build

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    env:
      CIBW_SKIP: cp27-win* pp27-win* cp36* cp37* cp38*
      CIBW_BUILD_VERBOSITY: 3

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'

      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install cibuildwheel
        run: |
          python -m pip install git+https://github.com/joerick/cibuildwheel.git@f6eaa9f
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl


  build_sdist:
    needs: [build_wheels]
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build sdist
        run: |
          python3 setup.py sdist
          # test whether tarball contains all files required for compiling
          pip3 install dist/rapidfuzz-*.tar.gz
          pip3 uninstall rapidfuzz --yes

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
